openapi: 3.0.3
info:
  version: 1.0.0
  title: Team API
  description: Team api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/datacalls:
    x-router-controller: dataCallsController
    get:
      description: Returns all datacalls
      operationId: getDataCalls
      responses:
        200:
          description: DataCall list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/datacall'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
               
  /api/v1/teams/{id}:
    x-router-controller: dataCallsController
    get:
      description: Returns a single datacall by its province
      operationId: findByprovince
      parameters:
        - required: true
          name: province
          description: province of the datacall to fetch
          in: path
          schema:
            type: string
      responses:
        200:
          description: DataCall found by province
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/datacall'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
 
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    datacall:
        type: object
        required:
          - province
        properties:
          province:
            type: string
          month:
            type: string
          phone_call_activation_organization:
            type: number
          telematic_activation_organization:
            type: number
          emergency_call:
            type: number
          year:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true